[package]
name = "server"
version = "0.1.0"
edition = "2018"
authors = ["Ryan Theodore The <ryan.the.2006@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
